# Generated by Django 2.1.2 on 2018-12-05 23:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=200)),
                ('precio', models.IntegerField(max_length=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad', models.IntegerField()),
                ('comentario', models.TextField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTienda.Sucursal')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTienda.Vendedor')),
            ],
        ),
    ]
