# Generated by Django 2.1.2 on 2018-12-05 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('Sucursal', models.ManyToManyField(to='AppTienda.Sucursal')),
            ],
        ),
        migrations.AlterField(
            model_name='oferta',
            name='descuento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTienda.Producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTienda.Producto'),
        ),
    ]
