# Generated by Django 2.1.2 on 2018-12-06 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0002_auto_20181205_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('correoElectronico', models.CharField(max_length=100)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppTienda.Vendedor')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Sucursal',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(default='a', max_length=200),
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
        migrations.AddField(
            model_name='producto',
            name='Tienda',
            field=models.ManyToManyField(to='AppTienda.Tienda'),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='Tienda',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='AppTienda.Tienda'),
        ),
        migrations.AddField(
            model_name='venta',
            name='tienda',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='AppTienda.Tienda'),
        ),
    ]
