# Generated by Django 2.1.2 on 2018-12-06 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0005_auto_20181205_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='encargado',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppTienda.Vendedor'),
        ),
    ]
