# Generated by Django 2.1.2 on 2018-12-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0006_auto_20181205_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
